services:
  n8n-gbs:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
    restart: unless-stopped
    networks:
      - n8n-network-gbs
 
networks:
  n8n-network-gbs:
    driver: bridge