version: '3.8'
services:
  coolify:
    image: coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    ports:
      - "3400:3400"
    volumes:
      - coolify-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Sao_Paulo  # Ajuste seu fuso horário
volumes:
  coolify-data: